services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}}
    ports:
      - '5432:5432'
    restart: always
    