spring:
  config:
    import: optional:classpath:profile_config.yaml

  application:
    name: order-service

  jpa:
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

server:
  port: 8081
