spring:
  config:
    import: optional:classpath:secrets_db.yaml

  application:
    name: order-service

  jpa:
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.102:9000

server:
  port: 8081
