server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    name: order-service

  jpa:
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.102:9000
