spring:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: always

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

logging:
  level:
    org:
      hibernate:
        SQL: WARN