spring:
  config:
    import: optional:classpath:secrets_auth.yaml

  application:
    name: authorization-server

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000

server:
  port: 9000